name: mindfullday_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.1

flutter_native_splash:
  backgroundColor: "#8696FE",
  image: "assets/images/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets\imagens\bg-login.png
    - assets\imagens\bg-home.png
    - assets\imagens\logo.png